### ISSUE TITLE
Rails support with something like react-rails

### ISSUE THREAD

**Issue by lexun** [zetachang/react.rb#22]
Any thoughts about adding support for Rails with something like https://github.com/reactjs/react-rails?

Is that something that you'd like to have included with this gem? Or should it be packaged separately?

**Comment by catmando** [comment]
What would this do exactly?  I have been using react.rb within rails, and I'm not seeing what react-rails would add.

**Comment by lexun** [comment]
I recall having to jump through some hoops to get react.js available in the browser with this gem in a rails environment, unless that was some sort of bug or mistake on my part.

Either way, in addition to just having it work with rails out of the box, I'm also looking at [rendering and mounting](https://github.com/reactjs/react-rails#rendering--mounting) and [server rendering](https://github.com/reactjs/react-rails#server-rendering) as pretty valuable features. Some people might also like the [generators](https://github.com/reactjs/react-rails#component-generator).

I suppose what I'm asking is that if someone wanted to add those things, would they be welcome in a pull request or do such rails specific additions belong in a separate gem?

**Comment by zetachang** [comment]
@lexun would you mind sharing any problem you are faced while using this within rails? Basically it should be easy if you are using [opal-rails](https://github.com/opal/opal-rails) and remember to require the react.js source inside `app/assets/javascripts/application.js`.

Also, given that this gem is designed to be used without rails, so I think most rails-relates features should belongs to a separate gem. Rendering [should not be a big problem](http://opalrb.org/docs/rails/#as-a-template), while server-side rendering is trickier, since we need to implement a version of `React.render` which run in server context.

**Comment by lexun** [comment]
Thanks David, I'll look into doing something separately for the rails specific featues. I'll also go back to the app I was working on where I was having issues and add a separate ticket once I'm able to confirm what was going on.

**Comment by gauravtiwari** [comment]
@catmando found your post on MetaRuby and I was wondering where can I find  the reactive-record gem? Is it published on rubygems?

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#22
