### ISSUE TITLE
propose changing define_state to simply state, and required_param to simply param

### ISSUE THREAD

**Issue by catmando** [zetachang/react.rb#85]
```ruby
state :foo, :bar  # syntax stays the same just drop the "define_"
param :baz, :type => String # by default params are required
param :baz, :required, :type => String # can explicitly say :required
param :user, :optional, :type => User # must say :optional or
param :user, default: nil, :type => User # if a default is given its also optional
```
(assuming params is kept as the react.rb access to props... if we change to props the above would be prop :user, etc)

**Comment by ajjahn** [comment]
Yep, I'm on board with this. Also, keep it param instead of prop. I agree with the point in made #83: 

> + params allows "props" to be for low level access to the actual react props hash

A param is a prop + observers, etc. If you need access to low level props, they're there as well.

Also, I may be in the minority, but I use and prefer the grape style params declarations in my own components. I vote to continue to support that, especially since both methods work exactly the same in the validator anyway.

**Comment by Thermatix** [comment]
I like this, always felt that `define_state` was a little redundant to be honest.

**Comment by catmando** [comment]
your third case would be an instance variable... 

More commments on state vs. prop under issue #83

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#85
