### ISSUE TITLE
Add ability to inherit instead of mixing in React::Component

### ISSUE THREAD

**Issue by catmando** [zetachang/react.rb#86]
To save typing it would be good to say:
```
class Foo < React::Base
...
end
```

I believe this is possible by simply doing this:

```ruby
class React::Base
  def self.inherited(child)
    child.instance_eval { include React::Component }
  end
end
```

The question is what should the class be called?  
React::Component::Base  (long)
React::Base
ReactComponent (odd)
React::Ruby (interesting)

???

**Comment by fkchang** [comment]
I like the brevity of React::Base and the accuracy of React::Component::Base
ReactComponent::Base ?

**Comment by ajjahn** [comment]
I believe you want `class_eval`. `class_eval` is a method on the Module class. The receiver will be a module or a class. `class_eval`'s block is evaluated in the context of the class. `instance_eval` is a method on the Object class. The receiver will be an object. `instance_eval`'s block is evaluated in the context of the object:

```
class Foo
  # class_eval block evaluated here
  class << self
    # instance_eval block evaluated here
  end
end
```
Another option, that I typically use is to just send the include message to the class directly:
```
class React::Component::Base
  def self.inherited(child)
    child.send(:include, React::Component)
  end
end
```

Instead of only creating a class for inheritance purposes, I think `React::Component` should just implement the `inherited` method directly. This would allow any custom component class that includes `React::Component` to be subclassed. Something like this (pseudo code warning!):

```
module React
  module Component
    def self.included(base)
      base.extend(ClassMethods)
    end

    module ClassMethods
      def included(child)
        child.send(:include, React::Component)
      end
    end

    class Base
      include React::Component
    end
  end
end
```
So:
```
class SubComponent < React::Component::Base; end

SubComponent.ancestors  # => [SubComponent, React::Component::Base, React::Component, ...]
```
Or:
```
class CustomBaseComponent
  include React::Component
end

class CustomSubComponent < CustomBaseComponent; end

CustomSubComponent.ancestors  # => [CustomSubComponent, CustomBaseComponent, React::Component, ...]
```

Oh, I also like `React::Component::Base`. I think that class belongs in the `React::Component` module.

**Comment by Thermatix** [comment]
Just FYI but you know you can do:

```ruby
class React::Ruby
  def self.included(child)
   child.include React::Component
  end
end
```

You don't need to do Eval's or send's or any weird complicated stuff, It works with `extend` as well.

**Comment by ajjahn** [comment]
@Thermatix There isn't anything attempting to inherit from a module in my example. In both cases, those components are inheriting from classes that include the module. When you include a module, it becomes an ancestor of the included class. Give this a try:

```ruby
module Foo
end

class Bar
  include Foo
end

Bar.ancestors # => [Bar, Foo, ...]
```

Good call on `child.include React::Component`. That's even better.
